name: ci

on:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - 
      name: Build the Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64
        tags: justdanz/curl-http3
        cache-from: |
          ghcr.io/justdanz/curl-http3:latest

    - 
      name: Verify Curl
      run: |
        docker run -t justdanz/curl-http3 curl --version | grep "curl 8.4.0"

    - 
      name: Verify Brotli support
      run: |
        docker run --rm justdanz/curl-http3 curl -sIL https://httpbin.org/brotli | grep -i 'content-encoding: br'

    - 
      name: Verify HTTP/3 support
      run: |
        docker run --rm justdanz/curl-http3 curl -sIL https://blog.cloudflare.com --http3 -H 'user-agent: mozilla' | grep 'HTTP/3'
